const CONFIG = {
  port: Number(process.env.PORT || 3000),
  binanceBaseUrl: process.env.BINANCE_BASE_URL || 'https://api.binance.com',
  tradingViewScannerBaseUrl: process.env.TRADINGVIEW_SCANNER_BASE_URL || 'https://scanner.tradingview.com',
  anthropicBaseUrl: process.env.ANTHROPIC_BASE_URL || 'https://api.anthropic.com',
  anthropicApiKey: process.env.ANTHROPIC_API_KEY || '',
  anthropicModel: process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-20250514',
  enableClaudeChat: process.env.ENABLE_CLAUDE_CHAT === 'true',
  emailProvider: process.env.EMAIL_PROVIDER || 'resend',
  resendApiKey: process.env.RESEND_API_KEY || '',
  emailFrom: process.env.EMAIL_FROM || 'XCapital AI <onboarding@resend.dev>',
  emailjsServiceId: process.env.EMAILJS_SERVICE_ID || '',
  emailjsTemplateId: process.env.EMAILJS_TEMPLATE_ID || '',
  emailjsPublicKey: process.env.EMAILJS_PUBLIC_KEY || '',
  emailjsPrivateKey: process.env.EMAILJS_PRIVATE_KEY || '',
  gmailUser: process.env.GMAIL_USER || '',
  gmailAppPassword: process.env.GMAIL_APP_PASSWORD || '',
  gmailSmtpHost: process.env.GMAIL_SMTP_HOST || 'smtp.gmail.com',
  gmailSmtpPort: Number(process.env.GMAIL_SMTP_PORT || 587),
  supabaseUrl: process.env.SUPABASE_URL || '',
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
  adminPlanKey: process.env.ADMIN_PLAN_KEY || '',
  allowDevOtp: process.env.ALLOW_DEV_OTP === 'true' || (!process.env.RENDER && process.env.NODE_ENV !== 'production'),
};

module.exports = { CONFIG };
